version: '3.5'

services:
  db:
   image: uniliva/oracle_db:12.2.0.1-se2
   container_name: oracle_db_12
   restart: always
   ports:
     - "1521:1521"
     - "5500:5500"
   volumes:
     - db_dados:/opt/oracle/oradata
     - ./scripts:/opt/oracle/scripts/startup
   environment:
     ORACLE_PWD: "unisenha"
   networks:
     - network-ucontas

networks:
  network-ucontas:
    driver: bridge

volumes:
  db_dados:
